---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: mhart/alpine-node
    tag: "6"

inputs:
- name: source
- name: out

caches:
- path: source/node_modules

run:
  path: ci/scripts/check.sh
  dir: source
